language: python
python:
  - "2.7"
  - "3.6"

os:
  - linux

# test for multiple blender versions
env:
  - BLENDER_VERSION=blender-2.79b BLENDER_DOWNLOAD=https://www.blend4web.com/blender/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2
# blender 2.8 build downloads don't have stable names, skip this for now
#  - BLENDER_VERSION=blender-2.80 BLENDER_DOWNLOAD=https://builder.blender.org/download//blender-2.80-35efa1d3d33-linux-glibc219-x86_64.tar.bz2

install:
  - pip install -r requirements.txt
  - wget ${BLENDER_DOWNLOAD}
  - mv blender-*.tar.bz2 blender.tar.bz2
  - tar xjf blender.tar.bz2
  - rm -f blender.tar.bz2
  - mv blender-* blender/

script:
  # add blender to path
  - export PATH=${PATH}:${PWD}/blender/
  - pytest --ignore=blender/
  - blender/blender -v
  - ./blendomatic.py export  --filenames "test_models/*.blend"
